@echo off
:vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error1.vbs
start error2.vbs
start error3.vbs
goto vbs